version: '3.9'
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        networks:
            backend:
                aliases:
                    - "postgres"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 15
            start_period: 15s
    swing-server:
        depends_on:
            db:
                condition: service_healthy
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - "80:80"
        environment:
            JDBC_DATABASE_URL: jdbc:postgresql://postgres/postgres
        networks:
            - backend
networks:
    backend:
        driver: bridge